.github/workflows/php.yml

This is a new codebase, so there's no reason to restrict linting to only changed files - ideally we want the whole codebase to be linted.

Simplify PHP lint action

---

inc/assets.php

This resolves an issue where WebPack uses `ws:` protocol but the Wikimedia Security Plugin only permits `wss`. This should be relaxed in the security plugin, but for now this PR will fix websocket terminal errors like this:

Fix CSP header for websocket connection

---

.github/workflows/release-develop.yml
.github/workflows/release.yml

Assets directory no longer exists following #8
There is also no practical reason to ship our package lockfile, it is not used outside of the build process

945: Fix build-to-release-branch workflow to match wp-scripts repo structure

---

.eslintrc

Fundamentally, code style does not represent a logic error. Prettier should not be tracked as an ESLint error because that makes it hard in-editor to distinguish between actual issues and stylistic things that will be solved by "npm run format".

Display Prettier issues as an ESLint "warning," not "error"

---

inc/blocks/core-group.php
plugin.php
src/blocks/core/group.js
src/blocks/expandable/index.js
src/editor.js
src/editor.scss
src/frontend.scss

Adds a new controls section to the group block as described in [WIKI-963](https://github.com/humanmade/wikimedia/issues/963)
Until we implement the ToC block, only the viewport height toggle will impact the editor. However, both items have an effect on the rendered markup.
- The ToC title will be slugified and set as an ID on the group, so that a ToC block may later link to it
- The group block will be set to `100vh` height and take up the full viewport width when that attribute is set
- In editor, the viewport height toggle should cause that element to expand in height. Test on both frontend and editor to understand how the preview plays out.
--------------
**Note**: This PR bundles a change to the Expandable block to enable it to be transformed from/to a Group block. This was added as a …

963: Add controls for setting a group block ToC name and full-height override

---

.github/actions/build-to-release-branch/action.yml
.github/actions/setup-node/action.yml
.github/actions/setup-php/action.yml
.github/workflows/node.yml
.github/workflows/php.yml
.github/workflows/release-develop.yml
.github/workflows/release.yml

While testing prior PRs in develop, I noticed that we only were deploying the CSS files in our build folder. This was a result of having a leftover line of theme-specific configuration in our `release` actions, which was not targeting the entire build folder as intended.
This PR corrects that issue, and also pins a number of other GH Action dependencies per the standards introduced while developing [WIKI-900](https://github.com/humanmade/wikimedia/issues/900)

945: Pin GH Action dependencies and fix file inclusion issue in release action

---

inc/assets.php
inc/editor/styles.php
plugin.php
src/editor.js
src/editor.scss
src/frontend-global.scss
src/frontend.js
src/styles/core-heading-report-section-heading.scss

This PR converts @philipjohn 's heading treatment into a block style, and sets up the scaffolding to handle styles efficiently. Makes a few asset loading changes to ensure our frontend styles can be previewed in-editor.
There are still some editor styling inconsistencies (see gap between colored group backgrounds) but I feel resolving these is out-of-scope for this project, and should be handled in Shiro.
Editor view:
Frontend view:

Introduce block style variations for repeated report elements

---

inc/editor.php
inc/report.php
plugin.php

This might be a basis for some of what @goldenapples was suggesting around further restricting where and when we enqueue or allow Report-based scripts, styles, PHP filters, and theme features. There's an unfinished piece where it won't work as early as `init()`, but should still be useful on many hooks.

Introduce a Reports\is_report_page() helper

---

inc/assets.php
inc/editor/patterns/financial-statements.php
inc/editor/patterns/report.php
src/blocks/expandable/frontend.scss
src/patterns/financial-statements.scss
src/styles/theme.scss

Fixes a couple of issues occurring on the dev site in order to fix maps and styles.
- Security exceptions are needed for blob:https://wikimediafoundation-org-develop.go-vip.co/ so that the map works correctly
- Use of mark for selecting inline font colours has a yellow background, needs to be made transparent
- Adds a cursor on hover for expandable buttons
- Fixes image spacing in one of the patterns

Fixes for the development site

---

inc/assets.php
package-lock.json
package.json
src/blocks/map/edit.js
src/blocks/map/view.js

The overrides to allow mapbox were added within a block of code that only runs locally. This PR adjusts how we set CSP headers to more precisely target the mapbox-related changes we need to make.
It also adds mapbox-gl as a direct dependency, to avoid having to eslint-ignore a benign error.

Correct CSP issues preventing mapbox usage on dev

---

inc/theme-integration.php
plugin.php
src/styles/theme.scss

Pairs with https://github.com/wikimedia/shiro-wordpress-theme/pull/143 to enable this plugin to suppress the page title from being output on report pages.
Also adjusts the styling of the fixed desktop nav, to better enable us to layer our own report-specific nav over it.
> [!NOTE]
> This does **not** remove or hide the desktop nav. It is still present in the report mobile designs, and removing it entirely prevents keyboard users from navigating back to other parts of the site; this did not feel intentional. Instead, we will layer our own "jump list" navigation elements over this one.

Template Integration: Integrate with Shiro to suppress page title

---

inc/editor/patterns/endowment.php
inc/editor/patterns/financial-statements.php
inc/editor/patterns/report.php
src/editor.scss
src/features/accordion.js
src/frontend-global.scss
src/frontend.js
src/patterns/accordion.scss

Implements an alternative accordion and updates the patterns for #992 and #995.
Also adds JS to open the first accordion item on load (as per the designs). 
To test:
- Insert the Endowment or Financial Statements block pattern
- Amend the content to match the design

#992 #985 - Accordions

---

inc/editor/patterns/endowment.php
inc/editor/patterns/financial-statements.php
inc/editor/patterns/previous-reports.php
inc/editor/patterns/report.php
src/blocks/expandable/frontend.scss
src/blocks/map/view.js
src/blocks/report-archive/block.json
src/blocks/report-archive/edit.js
src/blocks/report-archive/editor.scss
src/blocks/report-archive/index.js
src/blocks/report-archive/render.php
src/blocks/report-archive/view.js
src/blocks/report/block.json
src/blocks/report/edit.js
src/blocks/report/index.js
src/blocks/report/render.php
src/blocks/stories/render.php
src/blocks/stories/view.js
src/editor.scss
src/features/accordion.js
src/frontend-global.scss
src/frontend.js
src/patterns/accordion.scss
src/patterns/carousel.scss
src/patterns/financial-statements.scss
src/styles/report-archive.scss
src/styles/stories.scss

- Creates a block for the previous reports, which will infinitely scroll.
- Also addresses bugs in other carousels. 
To test:
- Insert the `Report Archive` block (or better still the Previous Reports Pattern)
- Add multiple slides and populate their contents. You will need to add a slide for each previous annual report.
- View the carousel on the front end, confirm that the infinite scroll works as expected, and the carousel will slide with touch on mobile.
Demo:
https://cln.sh/b0Xn9F3t1CzXBHtqlgkd

#988 - Previous Reports Carousel

---

src/blocks/thank-you/block.json
src/blocks/thank-you/edit.js
src/blocks/thank-you/index.js
src/blocks/thank-you/render.php
src/blocks/thank-you/style.scss
src/blocks/thank-you/view.js
src/types.js

This PR implements a custom animation block for the "Thank You!" text animation
Editor view, unselected
Editor view, selected
Frontend view
> [!NOTE]
> This block honors the "reduce motion" operating system preference

#979: "Thank you" text animation block

---

src/blocks/table-of-contents/frontend.scss
src/blocks/table-of-contents/save.js
src/frontend-global.scss
src/styles/core-columns.scss
src/styles/theme.scss

Implemented ToC styling, and fixes display of buttons in bottom-aligned column style variant
[Figma Design](https://www.figma.com/file/BhUZlGRtTPSmVtPqaxuPEt/Wikimedia-Foundation-Annual-Report?node-id=2320%3A1568&mode=dev) | Preview of this PR
-------- | ----------
[Figma Design](https://www.figma.com/file/BhUZlGRtTPSmVtPqaxuPEt/Wikimedia-Foundation-Annual-Report?node-id=1785%3A628&mode=dev) | Preview of this PR
-------- | ----------

#973: Implement table of contents styling

---

src/blocks/accordion-item/index.js
src/features/block-accordion.js
src/patterns/carousel.scss
src/styles/theme.scss

My customizations of Matt's carousel caused a bug because I used the wrong classname, and we need to revert the 'leave all items open' because it is only desired on certain accordions, not all. This structure permits the behavior to have multiple drawers open, when it IS needed:
- WMF Accordion
- WMF Accordion Item
- WMF Accordion
- WMF Accordion Item

Fix accordion issues

---

src/patterns/accordion.scss
src/patterns/wmf-accordion.scss

@mattwatsoncodes Please review the following, We _will not_ be using nth-child styling for accordion coloration. We'll use utility classes added to the `WMF Accordion Item` block, available from this list here.

Accordion: Revert WEND change that broke accordion coloring

---

src/blocks/overlay/render.php
src/blocks/overlay/view.js
src/features/share-button.js
src/frontend-global.scss
src/frontend.js
src/styles/core-buttons.scss

Provides a minimally styled share button which can be wired up by adding the class name "is-share-button" to a button.
If this class is set on the button, clicking it will copy the current URL to the user's clipboard and briefly update the button text to say "Copied!".

Copy URL to clipboard when share button is clicked

---

src/editor.scss
src/features/by-the-numbers.js
src/formats/countup-number/view.js
src/patterns/by-the-numbers.scss

Using this checklist: https://hmn.slack.com/archives/C06E97QQMTR/p1712777594942299?thread_ts=1712756324.263479&cid=C06E97QQMTR
This PR sorts the following:
- Attempts to add an exact estimation of the design spacing for desktop and mobile.
- Allows animations to reverse when scrolled out of frame
I will add a comment to this PR with editor markup that introduces other animations.
See side-by-side comparisons.

By the numbers imporovements

---

src/blocks/table-of-contents/_jumplist.scss

Jumplist: Position properly when admin bar not present

---

src/features/datavis-interaction-2023.js

This causes a JS error on non-report pages, and should not.

Visualization: Prevent datavis-accordion connector from running when not on right page.

---

plugin.php
src/helpers/variables.scss
src/patterns/accordion.scss
src/patterns/by-the-numbers.scss
src/patterns/carousel.scss
src/patterns/letter-from-the-ceo.scss
src/patterns/welcome-page.scss
src/patterns/wmf-accordion.scss
src/patterns/wrapped.scss
src/styles/endowment-overrides.scss
src/styles/theme.scss

iOS is rendering this font at a strangely bold level. Chrome treats the font as 'normal' weight at 600 and below, but iOS only bolds it to the correct degree at 600 specifically.

Address iOS font rendering issue

---

src/blocks/overlay/view.js

When we detect hover intent on an overlay open button, preemptively place the images into a visually-hidden frame in the document so that they are downloaded and ready by the time we render the overlay itself.

Preload images in overlays

---

src/features/by-the-numbers.js
src/formats/countup-number/view.js

@mattwatsoncodes After your comment that the 200ms delay may not be needed, I observed that deferring the initialization of the masonry was not strictly necessary either. This actually delays DOMContentLoaded, but it does cause the page to render correctly, sooner, on desktop.

Masonry performance

---

src/blocks/map/view.js
src/blocks/stories/view.js

There was a situational fatal on WEND because the draft report there does not contain a stories section, and the relevant code did not guard that the element existed before running.
There is also a situation where a malformed anchor hash would be added to the document while opening a slide.

Fix two issues observed while testing

---

src/features/block-accordion.js
src/features/datavis-interaction-2023.js
src/helpers/scroll-to-element.js

This PR fixes a mismatch in how we identify the visualization `view` element to make the logic for opening accordion on chart click work again.
It also adjusts the accordion anchoring to be only as-needed, so that the chart does not always scroll out of view.

Datavis interaction

---

src/blocks/map/edit.js
src/blocks/map/view.js

Adds a `click` event handler to the map clusters so that the map will zoom in and break them apart when they are clicked.
Caveat: If two pins have the exact same coordinates, this will not work, so there is some responsibility on the data configuration to ensure each pin has a unique location. 
Note about DRY: There is likely now enough map code reuse to justify separating it into it's own JavaScript object and calling its methods on the front and back end of the site, however this refactor would take time that I know we are short of. Mentioning here so that we can put this into the retainer as a ticket.

Enable zoom on cluster click

---

inc/report.php

The page `about/annualreport/`, which is the reports archive, seems to be getting _alternately_ matched with the changes from #92 where we tried to set `annualreport` as the CPT base. This causes a redirect loop that prevents the page from loading.
Adding an `s` to pluralize the virtual "folder" in which the reports pages live fixes the issue, but is a bit of a hack. @goldenapples have you found other ways to combat this type of redirect loop? I've seen issues with priority, but never a back-and-forth redirect loop like this.
(Also took the opportunity to add more nuanced label strings to the CPT)

Fix Report rewrite slug redirect loop with annual report archive page

---

src/blocks/thank-you/style.scss
src/blocks/thank-you/view.js

https://github.com/wikimedia/wikimedia-wordpress-annual-report-plugin/assets/442115/bd97a708-2522-4221-9c15-e16ad5c4c293
Per feedback:
> The Thank you carousel is moving rather slowly and there's a small pause every time we see the word in a new language.
>
> Please update this so that it moves more smoothly: move between each different language a bit faster and without making a pause.
Settled on 1200ms after discussion and review with @sacmp in Slack.
As an aside, I'm quite happy that this makes the code so much simpler!

Make thank-you text carousel faster and smoother

---

plugin.php

- Version contains wikimedia/wikimedia-wordpress-annual-report-plugin#95
- Version contains wikimedia/wikimedia-wordpress-annual-report-plugin#94 and wikimedia/wikimedia-wordpress-annual-report-plugin#92 to change rewrite slug to annualreports/

Bump plugin version for asset cachebusting

---

inc/assets.php

This PR makes some forward-looking adjustments in preparation for upcoming changes to the security plugin, which will allow the CSP filtering done in this plugin to be simplified.
- Fix a bug where blob: would be added incorrectly if a `worker-src` directive was already present
- Avoid mutating the CSP header string at all if it already has the necessary `worker-src blob:` directive

Fix security policy adjustments to avoid malformed worker-src directive

---

package-lock.json
package.json
src/blocks/animation/editor.scss
src/blocks/core/group.js
src/blocks/map/block.json
src/blocks/map/edit.js
src/blocks/map/render.php
src/blocks/stories/edit.js
src/blocks/stories/render.php
src/blocks/stories/style.scss
src/blocks/stories/view.js
src/blocks/story/edit.js
src/components/inner-block-slider/inner-block-single-display.js
src/editor.scss
src/helpers/colors.scss
src/patterns/wmf-accordion.scss
src/styles/report-archive.scss

- Allows map projection to be edited (now defaults to equirectangular)
- Fix issue where clicking "forward" on story or map caused entire unit to disappear 🙀 
- Fix JS errors when content not fully populated
- Do not show arrows on stories when only one story is present
- Restore Group Label field on parent groups so that anchors in stories and maps work
- Make editor map coords same as frontend
- Set min-height on map on frontend and backend so that coordinates work as expected (unblocks storing the map position, as a followup)
Per @sacmp special request, I intend to merge this through to PreProd without full initial code review so she can test in that environment. Requesting ex-post-facto code review.

1040: Resolve remaining issues with Report blocks outside Report section

---

src/styles/endowment-overrides.scss

Using the global variable caused several media queries to kick in at the wrong time, and constrained the page overall. The local version of the variable should have been left alone in #99 .
**Before**
> <img width="923" alt="image" src="https://github.com/user-attachments/assets/b4d30685-f8ad-4be6-a28f-a9b50d1a565d">
**After**
> <img width="923" alt="image" src="https://github.com/user-attachments/assets/c523df4a-a7f8-4783-849d-7f2685f9a6a5">

WIKI-1046: Use endowment-specific max width, not global WMF variable

---

.github/actions/setup-node/action.yml
.github/actions/setup-php/action.yml

4.0.1 was recently deprecated, see https://github.com/actions/cache/discussions/1510

Bump `actions/cache` to v4.2.2

---

src/styles/core-image.scss
src/styles/report-2022-2023.scss

Updates the report image style variant to allow colour management by wrapping in a group block, accommodate for full-width images. Border radius removed in #104

#1066 Report image styling

---

src/blocks/table-of-contents/edit.js
src/components/palette-color-picker/index.js
src/components/palette-color-picker/readme.md

This PR extracts the color picker component from #110 and makes it reusable, hopefully useful for introducing additional color controls to other blocks.

Refactor ToC color picker component into reusable palette picker

---

src/styles/endowment-overrides.scss

- Adds `alignfull` support to the hero image, so it bleeds to the right side of the screen.

#1075 WEND Hero image 

---

src/blocks/expandable/block.json
src/blocks/expandable/deprecated/index.js
src/blocks/expandable/deprecated/v1.js
src/blocks/expandable/edit.js
src/blocks/expandable/frontend.scss
src/blocks/expandable/index.js
src/blocks/expandable/save.js
src/blocks/stories/block.json
src/blocks/stories/edit.js
src/blocks/stories/render.php
src/blocks/stories/style.scss
src/styles/report-2022-2023.scss

- Allows the colours of the navigation section to be customisable
- Allows the fade colour of the expanded content to be customisable
Note: The 2022-2023 report inverted the colour of the icon on hover/active, since the text went from black to white. Now the colour is controlled in the editor, but there is no way to update the icon using this colour since it is an `<img>`.

#1065 Story section colours

---

src/helpers/colors.scss

In the Shiro theme, some colours are set to a different colour value to what is visible in the editor. This causes unexpected results when publishing. Here we are overriding those values to match the editor. This is a temporary solution and should be resolved in the theme.
See:
- https://github.com/wikimedia/shiro-wordpress-theme/blob/main/assets/src/sass/helpers/_style-guide-variables-overrides.scss
- https://github.com/wikimedia/shiro-wordpress-theme/blob/main/inc/editor/namespace.php
Differences:
Updated colours:

#1084 Fix frontend colours

---

src/patterns/by-the-numbers.scss

Removes additional padding around By The Numbers section so it aligns with the rest of the content.
Before:
After:

#1051 Fix By The Numbers section alignment

---

src/styles/endowment-overrides.scss

Allow Endowment report hero image to strech full-wide on mobile

---

src/blocks/stories/render.php
src/blocks/stories/view.js

Wraps the initializing javascript for this block in a loop so that it's initialized separately for each instance of the block on a page.
(The changes look like a lot, but they're 99% whitespace changes - review [this view](https://github.com/wikimedia/wikimedia-wordpress-annual-report-plugin/pull/128/files?diff=unified&w=1) to see what actually changes.)

Allow "stories" carousel block to be used more than once on a page

---

src/blocks/map/block.json
src/blocks/map/edit.js
src/blocks/map/render.php
src/blocks/map/view.js
src/blocks/stories/view.js

We still have some hard-coded values from the 2022-2023 annual report which will complicate using the map in any other context. As a parallel to #130, this PR makes the centerpoint and initial zoom level configurable in the same manner as projection. We can deploy this to the existing sites and update the historical content as follows,
- Center: lat 9 / lon 8.18 for WMF, lat 9 / lon 26.83 for WEND
- Zoom: 0.5 for both
- Projection: equirectangular for both
and then customize as needed for future usages.

1112: Make map values configurable to enable variance per-usage

---

inc/editor/patterns/welcome-page.php
src/patterns/hero.scss
src/patterns/welcome-page.scss
src/styles/theme.scss

https://github.com/humanmade/Wikimedia/issues/1124
Miscellaneous annual report fixes for the UX Refresh, mostly to the annual reports home page.
Related PR:
https://github.com/wikimedia/wikimedia-wordpress-annual-report-plugin/pull/133
https://github.com/wikimedia/shiro-wordpress-theme/pull/211
Testing:
https://wikimediafoundation-org-develop.go-vip.co/about/annualreport/
https://wikimediafoundation-org-develop.go-vip.co/annualreports/2022-2023-annual-report/

1124: UX Refresh Annual Report plugin fixes

---

src/patterns/carousel.scss

Tiny fix for the annual reports maps and stories carousel buttons, so they don't overlap the main menu.

Hotfix: Fix z-index overlapping main navigation
