wikimedia/wikimedia-wordpress-annual-report-plugin

.github/workflows/php.yml
inc/assets.php
inc/report.php

Fixes two build errors, one of which was causing fatals after #1 was merged.

Fix build errors

---

LICENSE
composer.json
package.json
plugin.php

Add GPLv2 as LICENSE file and standardize/correct SPDX license strings

---

inc/editor/patterns.php
inc/editor/patterns/letter-from-the-ceo.php
inc/report.php
plugin.php
src/editor.scss
src/frontend.scss
src/helpers/variables.scss
src/patterns/hero/frontend.scss
src/patterns/letter-from-the-ceo/editor.scss
src/patterns/letter-from-the-ceo/frontend.scss

Adds a new pattern, "Letter from the CEO" containing a heading (h2), quote, profile block and expandable block (removable). It's all locked down except for the text, the person used for the profile and the expandable block that can be swapped out for just normal content.
**Note:** Locally I have some issues inserting the pattern. Please let me know if you see any issue with that.
**Note:** I've branched off of the hero pattern branch because we need the Patterns scaffolding.

Letter from the CEO Pattern

---

inc/editor/colors.php
src/helpers/colors.scss

This updates the color values which have changed since #22, and introduce missing Green30 color which was not available in Shiro's color palette

Colors: Restore missing colors and update changed ones

---

inc/assets.php
src/blocks/marker/edit.js
src/blocks/overlay/edit.js
src/blocks/story/edit.js
src/patterns/overlay.scss
src/styles/endowment-overrides.scss

Style Pass and Creation of Home Page Welcome Block

Style Pass and Creation of Home Page Welcome Block

---

src/blocks/marker/edit.js
src/blocks/overlay/edit.js
src/blocks/story/edit.js

Fix issue with WEND post select, justs adds a conditional.

Fix issue with WEND post select

---

src/blocks/marker/edit.js
src/blocks/overlay/edit.js
src/blocks/story/edit.js

Forgot to put in a fallback, now sorted.

Fix WEND post select bug

---

src/styles/theme.scss

This media query does not get picked up when logged out. It seems to have the 'only' directive, but others do not. 
Cannot test locally, so will have to push to develop to test.

Fixed media query screen issue

---

src/styles/theme.scss

Debug margin issue

---

src/editor.scss
src/patterns/carousel.scss
src/patterns/donate.scss
src/patterns/overlay.scss
src/patterns/welcome-page.scss
src/styles/core-image.scss
src/styles/endowment-overrides.scss
src/styles/theme.scss

Found an issue with calc that impacted media queries on the VIP environment.
This PR should hopefully fix them.

Remove calc from media queries

---

src/blocks/table-of-contents/_jumplist.scss
src/blocks/table-of-contents/view.js
src/helpers/scroll-to-element.js
src/styles/theme.scss

Header fixes: Jumplist pinning & ToC / "show less" anchoring

---

inc/assets.php
plugin.php
src/patterns/by-the-numbers.scss
src/patterns/letter-from-the-ceo.scss

Before | After
------ | ------

Spacing and typography fixes for Letter from CEO and By the Numbers

---

src/blocks/report-archive/view.js

Exagerate the left-right scroll so that an accidental drift during vetical scroll does not trigger carousel

Fix accidental archive carousel trigger

---

src/blocks/map/view.js
src/styles/endowment-overrides.scss

Styles from the WEND feedback document: https://docs.google.com/document/d/1xSC8N8wdI7gkYqGlcCEWzggpvt6koDBa97pQNwVcerM/edit

WEND design feedback

---

src/styles/endowment-overrides.scss

Results of internal HM feedback

Wend additional feedback

---

src/formats/countup-number/view.js

We have often had reports that the spinner does not play at all, and observed that at certain sizes (if the text is slightly larger than the screen) it may loop infinitely because the number itself is wide enough that it overlaps the edges of the column and becomes considered to be "out of view" by the observer.
This PR attempts to address those problems by doing three things, of which only two probably make a difference:
- Refactor the module so that we keep a Map of instantiated CountUp animations, to avoid re-instantiating every time the listener runs (this probably doesn't fix the bug but avoids a little processing on scroll, which has become a bit janky with all the other stuff running on this page)
- Change the trigger threshold to 0.9 so that we have more leeway to avoid …

Address issue where spinner plays infinitely in certain cases

---

inc/editor/patterns/welcome-page.php
src/helpers/scroll-to-element.js
src/patterns/hero.scss
src/patterns/welcome-page.scss
src/styles/theme.scss

- Fix scrolling anchoring
- Fix hero styling
- Update pattern

Welcome page fixes

---

src/blocks/overlay/render.php
src/styles/core-buttons.scss

Requested
- Remove exclamation mark
- Edit text of story share button

Text adjustments

---

src/blocks/table-of-contents/_jumplist.scss
src/styles/core-buttons.scss
src/styles/endowment-overrides.scss

Address three pieces of feedback on the WEND sites

WEND feedback

---

src/blocks/overlay/render.php
src/features/share-button.js
src/styles/endowment-overrides.scss

Also adds highlighting to the active element on WEND, as requested.

ToC: Share button in Jumplist should not link to a specific anchor

---

inc/report.php

Thumbnail and excerpt are required so WMF team can properly configure the oembed content.
Experiments with adjusting the reports slug.

Report post type supports

---

inc/report.php
src/patterns/welcome-page.scss
src/styles/endowment-overrides.scss

~~This is a draft PR because it is not confirmed what the target URL should be _across sites_. May need to take a different approach if the change is needed foundation-only.~~
Approved rewrite base is `/annualreport/`, per @sacmp

Report: Adjust CPT rewrite to position reports in "annualreport/"

---

src/styles/core-image.scss
src/styles/report-2022-2023.scss

Fix a couple of small linting issues found when running `nom run lint` locally.

Fix linting issues

---

src/patterns/hero.scss

Allows the border to use the same colour as the adjacent text, which is customisation in the editor.

#1063 Hero border colour

---

src/blocks/animation/block.json
src/blocks/animation/edit.js
src/blocks/animation/index.js
src/blocks/animation/view.js
src/patterns/hero.scss

- Adds full width support to embedded animations
- Adds support for looped animations

#1064 Animated Hero

---

inc/editor/colors.php
src/helpers/colors.scss

Adds Gold to WEND colour palette.

#1070 Colour palette

---

src/styles/endowment-overrides.scss

Adds support for `alignfull` images with captions.

#1074 WEND full-width images

---

src/blocks/map/block.json
src/blocks/map/edit.js
src/blocks/map/render.php
src/blocks/map/style.scss
src/patterns/carousel.scss
src/styles/endowment-overrides.scss

- Allows the map marker colour to be customisable

#1068 Maps colours

---

src/styles/endowment-overrides.scss

Fixes hover/active states for icons.

Invert Story icons on WEND

---

src/blocks/expandable/frontend.scss
src/styles/report-2022-2023.scss

Restricts hard-coded grey colour to the 2022-2023 report.

#1065 Fix fade colour

---

src/patterns/welcome-page.scss

https://github.com/humanmade/Wikimedia/issues/1124
Fixes a couple more font and spotlight section issues for the Annual Report homepage.

1124: Fix annual report homepage fonts, spotlight
